name: "flow_network"
platform: "onnxruntime_onnx"
max_batch_size: 0

input [
  {
    name: "onnx::Gemm_0",
    data_type: TYPE_FP32,
    dims: [4,2]
  }
]

output [
  {
    name: "57",
    data_type: TYPE_FP32,
    dims: [4,3]
  }
]

